### ISSUE TITLE
Front-end Framework Transition

### ISSUE THREAD

**Issue by sergeyklay** [sergeyklay/promptly#15]
- [x] Research and select a more established CSS framework (e.g., Bootstrap, Tailwind CSS, or Bulma).
- [x] Plan the transition including identifying all the areas of the application that will be affected.
- [x] Make necessary changes in the codebase to replace MaterializedCSS with the chosen framework.
- [ ] Thoroughly test the application to ensure that the transition has not caused any regressions.

**Tasks:**

- [ ] #27
